-- CREATE DATABASE IF NOT EXISTS
CREATE DATABASE IF NOT EXISTS CLASSROOM_ADMIN;

-- USE DATABASE
USE CLASSROOM_ADMIN;

-- TABLE CENTER
CREATE TABLE CENTER(
  cif VARCHAR(9) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  direction VARCHAR(255) NOT NULL,
  postal_code INT(5) NOT NULL,
  city VARCHAR(100) NOT NULL,
  province VARCHAR(100) NOT NULL
);

-- TABLE COURSE
CREATE TABLE COURSE(
  code VARCHAR(10) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  cif_center VARCHAR(9) NOT NULL,
  CONSTRAINT course_cif_center_fk FOREIGN KEY (cif_center) REFERENCES CENTER(cif)
);

-- TABLE STUDENT
CREATE TABLE STUDENT(
  dni VARCHAR(9) PRIMARY KEY,
  pass VARCHAR(255) NOT NULL,
  name VARCHAR(50) NOT NULL,
  surnames VARCHAR(100),
  phone VARCHAR(20),
  email VARCHAR(100) NOT NULL UNIQUE,
  birthdate DATE,
  code_course VARCHAR(10),
  CONSTRAINT student_code_course_fk FOREIGN KEY (code_course) REFERENCES COURSE(code)
);

-- TABLE ROLE
CREATE TABLE ROLE(
  id INT PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

-- TABLE TEACHER
CREATE TABLE TEACHER(
  dni VARCHAR(9) PRIMARY KEY,
  pass VARCHAR(255) NOT NULL,
  name VARCHAR(50) NOT NULL,
  surnames VARCHAR(100),
  phone VARCHAR(20),
  email VARCHAR(100) NOT NULL UNIQUE,
  birthdate DATE,
  id_role INT,
  CONSTRAINT teacher_id_role_fk FOREIGN KEY (id_role) REFERENCES ROLE(id)
);

-- TABLE TEACHER_COURSE
CREATE TABLE TEACHER_COURSE(
  dni_teacher VARCHAR(9),
  code_course VARCHAR(10),
  PRIMARY KEY(dni_teacher, code_course),
  CONSTRAINT teacher_course_dni_teacher_fk FOREIGN KEY (dni_teacher) REFERENCES TEACHER(dni),
  CONSTRAINT teacher_course_code_course_fk FOREIGN KEY (code_course) REFERENCES COURSE(code)
);

-- TABLE FLOOR
CREATE TABLE FLOOR(
  id INT AUTO_INCREMENT PRIMARY KEY,
  floor_number INT(2),
  cif_center VARCHAR(9) NOT NULL,
  CONSTRAINT floor_cif_center_fk FOREIGN KEY (cif_center) REFERENCES CENTER(cif)
);

-- TABLE ROOM
CREATE TABLE ROOM(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50),
  seats_number INT(2),
  type VARCHAR(10),
  id_floor INT,
  CONSTRAINT room_id_floor_fk FOREIGN KEY (id_floor) REFERENCES FLOOR(id)
);

-- TABLE SEAT
CREATE TABLE SEAT(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50),
  id_room INT,
  CONSTRAINT seat_id_room_fk FOREIGN KEY (id_room) REFERENCES ROOM(id)
);
