-- CREATE DATABASE IF NOT EXISTS
CREATE DATABASE IF NOT EXISTS CLASSROOM_ADMIN;

-- USE DATABASE
USE CLASSROOM_ADMIN;

-- TABLE CENTER
CREATE TABLE CENTER(
  CIF VARCHAR(9) PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  DIRECTION VARCHAR(255) NOT NULL,
  POSTAL_CODE INT(5) NOT NULL,
  CITY VARCHAR(100) NOT NULL,
  PROVINCE VARCHAR(100) NOT NULL
);

-- TABLE COURSE
CREATE TABLE COURSE(
  CODE VARCHAR(10) PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  CIF_CENTER VARCHAR(9) NOT NULL,
  CONSTRAINT COURSE_CIF_CENTER_FK FOREIGN KEY (CIF_CENTER) REFERENCES CENTER(CIF)
);

-- TABLE STUDENT
CREATE TABLE STUDENT(
  DNI VARCHAR(9) PRIMARY KEY,
  PASS VARCHAR(255) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  SURNAMES VARCHAR(100),
  PHONE VARCHAR(20),
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  BIRTHDATE DATE,
  CODE_COURSE VARCHAR(10),
  CONSTRAINT STUDENT_CODE_COURSE_FK FOREIGN KEY (CODE_COURSE) REFERENCES COURSE(CODE)
);

-- TABLE ROLE
CREATE TABLE ROLE(
  ID INT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL
);

-- TABLE TEACHER
CREATE TABLE TEACHER(
  DNI VARCHAR(9) PRIMARY KEY,
  PASS VARCHAR(255) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  SURNAMES VARCHAR(100),
  PHONE VARCHAR(20),
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  BIRTHDATE DATE,
  ID_ROLE INT,
  CONSTRAINT TEACHER_ID_ROLE_FK FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID)
);

-- TABLE TEACHER_COURSE
CREATE TABLE TEACHER_COURSE(
  DNI_TEACHER VARCHAR(9),
  CODE_COURSE VARCHAR(10),
  PRIMARY KEY(DNI_TEACHER, CODE_COURSE),
  CONSTRAINT TEACHER_COURSE_DNI_TEACHER_FK FOREIGN KEY (DNI_TEACHER) REFERENCES TEACHER(DNI),
  CONSTRAINT TEACHER_COURSE_CODE_COURSE_FK FOREIGN KEY (CODE_COURSE) REFERENCES COURSE(CODE)
);

-- TABLE FLOOR
CREATE TABLE FLOOR(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FLOOR_NUMBER INT(2),
  CIF_CENTER VARCHAR(9) NOT NULL,
  CONSTRAINT FLOOR_CIF_CENTER_FK FOREIGN KEY (CIF_CENTER) REFERENCES CENTER(CIF)
);

-- TABLE ROOM
CREATE TABLE ROOM(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50),
  SEATS_NUMBER INT(2),
  TYPE VARCHAR(10),
  ID_FLOOR INT,
  CONSTRAINT ROOM_ID_FLOOR_FK FOREIGN KEY (ID_FLOOR) REFERENCES FLOOR(ID)
);

-- TABLE SEAT
CREATE TABLE SEAT(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50),
  ID_ROOM INT,
  CONSTRAINT SEAT_ID_ROOM_FK FOREIGN KEY (ID_ROOM) REFERENCES ROOM(ID)
);
